pipeline{
    agent { label 'JDK-17'}
    tools {
        jdk 'JDK-17'
        maven 'mvn'
    }
       
    triggers { pollSCM('* * * * *')}
stages{
    stage('git'){
        steps{
            git branch: 'main',
                url: 'https://github.com/spring-projects/spring-petclinic.git'              
        }
    }    
    stage('Build Maven Project'){
        steps{
            rtMavenDeployer (
                id: "maven-ID",
                serverId: "JFROG",
                releaseRepo: 'qtdevops-libs-release-local',
                snapshotRepo: 'qtdevops-libs-snapshot-local',
                )
            rtMavenRun (
                tool: 'mvn',
                pom: 'pom.xml',
                goals: 'clean install',
                deployerId: "maven-ID",
                )
            rtPublishBuildInfo (
                serverId: "JFROG"
            )    
        }
    }    
    stage('reporting') {
            steps {
                junit testResults: '**/target/surefire-reports/TEST-*.xml'
            }
        }    
    }
}


    
